### ISSUE TITLE
description is misleading

### ISSUE THREAD

**Issue by 89z** [WilliamVenner/sysreq#1]
> Simple, virtually-zero-dependencies HTTP client wrapping a system client for Rust 

Crate currently has these dependencies:

~~~
1       lazy_static v1.4.0
2       thiserror v1.0.34
3       thiserror-impl v1.0.34 (proc-macro)
4       proc-macro2 v1.0.43
5       unicode-ident v1.0.3
6       quote v1.0.21
7       syn v1.0.99
8       url v2.3.0
9       form_urlencoded v1.0.1
10      matches v0.1.9
11      percent-encoding v2.1.0
12      idna v0.2.3
13      unicode-bidi v0.3.8
14      unicode-normalization v0.1.21
15      tinyvec v1.6.0
16      tinyvec_macros v0.1.0
~~~

which is actually higher than a few other options:

- `http_io`
- `http_req`
- `minreq`
- `oxhttp`

in addition, this crate requires an external command such as cURL. I think the description should be modified to reflect the reality of this crate.

**Comment by WilliamVenner** [comment]
These are already explained in the README. The "dependency" on cURL is not required.

**Comment by WilliamVenner** [comment]
thiserror was definitely unnecessary though: https://github.com/WilliamVenner/sysreq/commit/fb5139a782ba78e8d704a6256bc24588242bb0c3
